[install]
# Install packages from npm registry
registry = "https://registry.npmjs.org/"

# Always install exact versions
exact = true

# Use cache for faster installs
cache = true

# Test configuration removed - now using Vitest instead of bun:test

[build]
# Build configuration for production
minify = true
sourcemap = true
target = "node"
